function matRad_saveAllPlanes(hFig, exportFolder, resolution)
% matRad_saveAllPlanes - Save all plane figures from matRad_showAllPlanes to folder
%
% Syntax:
%   matRad_saveAllPlanes(hFig, exportFolder)
%   matRad_saveAllPlanes(hFig, exportFolder, resolution)
%
% Description:
%   Saves all figures generated by matRad_showAllPlanes (or similar multi-plane
%   viewers) to a specified export folder with timestamped filenames.
%   Loops through all planes (axial, coronal, sagittal) and figure sets,
%   sanitizes figure names, and exports as PNG with optional resolution control.
%
% Inputs:
%   hFig         - struct with figure handles per plane (output from matRad_showAllPlanes)
%                  Expected structure: hFig.axial(i).fig, hFig.coronal(i).fig, etc.
%   exportFolder - char/string, path to folder where figures will be saved
%   resolution   - (optional) numeric, DPI for export (default: 200)
%
% Outputs:
%   None (figures are saved to disk)
%
% Notes:
%   - Filenames follow pattern: <FigureName>_yyyy-mm-dd_HHMM.png
%   - Special characters in figure names are replaced with underscores
%   - Uses exportgraphics for higher quality output than saveas
%   - If exportFolder does not exist, it will be created
%
% Reference List Entry:
%   Previous Name: N/A
%   Current Name : matRad_saveAllPlanes
%   Description  : Save all plane figures from matRad_showAllPlanes to folder
%   Call         : matRad_saveAllPlanes(hFig, exportFolder, resolution)
%   Status       : 🟢
%
% -------------------------------------------------------------------------
% Author: Joana Leitão
% Date: 2025-11-13_0000
% -------------------------------------------------------------------------

    % Input validation
    if nargin < 2
        error('matRad_saveAllPlanes:NotEnoughInputs', ...
              'Provide hFig (figure struct) and exportFolder (path).');
    end
    if nargin < 3 || isempty(resolution)
        resolution = 200; % default DPI
    end

    % Ensure export folder exists
    if ~isfolder(exportFolder)
        mkdir(exportFolder);
        fprintf('📁 Created export folder: %s\n', exportFolder);
    end

    % Get all plane names (e.g., 'axial', 'coronal', 'sagittal')
    planeNames = fieldnames(hFig);

    % Loop through each plane
    for p = 1:numel(planeNames)
        plane = planeNames{p};
        planeStruct = hFig.(plane);

        % Some planes might have multiple figure sets (1×N struct array)
        for f = 1:numel(planeStruct)
            figHandle = planeStruct(f).fig;

            % Validate figure handle
            if ~isvalid(figHandle)
                warning('matRad_saveAllPlanes:InvalidFigure', ...
                        'Skipping invalid figure handle for %s(%d).', plane, f);
                continue;
            end

            % Clean figure name: replace special characters with underscores
            figName = figHandle.Name;
            if isempty(figName)
                figName = sprintf('%s_fig%d', plane, f);
            end
            figName = regexprep(figName, '[^\w]', '_');

            % Generate timestamped filename following pattern yyyy-mm-dd_HHMM
            timestamp = datestr(now, 'yyyy-mm-dd_HHMM');
            saveName = sprintf('%s_%s.png', figName, timestamp);
            savePath = fullfile(exportFolder, saveName);

            % Save figure using exportgraphics (higher quality than saveas)
            try
                exportgraphics(figHandle, savePath, 'Resolution', resolution);
                fprintf('✅ Saved %s\n', saveName);
            catch ME
                warning('matRad_saveAllPlanes:SaveFailed', ...
                        'Failed to save %s: %s', saveName, ME.message);
            end
        end
    end

    fprintf('✅ All figures saved to: %s\n', exportFolder);
end